apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  environment: prod
  app.kubernetes.io/instance: test-app-prod

namespace: test-app-prod

nameSuffix: -prod

patchesStrategicMerge:
  - patch-deployment.yaml